site_name: maddy

repo_url: https://github.com/foxcpp/maddy

theme: readthedocs

markdown_extensions:
  - codehilite:
      guess_lang: false

nav:
  - Tutorials:
    - tutorials/setting-up.md
    - tutorials/building-from-source.md
    - tutorials/alias-to-remote.md
    - tutorials/pam.md
  - Release builds: 'https://maddy.email/builds/'
  - Integration with software:
    - third-party/dovecot.md
    - third-party/smtp-servers.md
    - third-party/rspamd.md
    - third-party/mailman3.md
  - seclevels.md
  - faq.md
  - multiple-domains.md
  - unicode.md
  - upgrading.md
  - specifications.md
  - openmetrics.md
  - Manual pages:
    - man/_generated_maddy.1.md
    - man/_generated_maddy.5.md
    - man/_generated_maddy-auth.5.md
    - man/_generated_maddy-blob.5.md
    - man/_generated_maddy-config.5.md
    - man/_generated_maddy-filters.5.md
    - man/_generated_maddy-imap.5.md
    - man/_generated_maddy-smtp.5.md
    - man/_generated_maddy-storage.5.md
    - man/_generated_maddy-targets.5.md
    - man/_generated_maddy-tables.5.md
    - man/_generated_maddy-tls.5.md
  - Internals:
    - internals/quirks.md
    - internals/sqlite.md
